dataset:
  data_path: "./data/dataset/"
  VA_label_path: "./data/annotations_VA/"
  seq_len: 80
  mean: [0.367035294117647, 0.41083294117647057, 0.5066129411764705]
  std: [1, 1, 1]
  size: 224
  save_batch_fig: False

train_params:
  debug: False
  seed: 2021
  gpu_id: 0
  batch_size: 128
  n_epochs: 15
  criterion: ccc
  ccc_eps: 1e-5
  num_workers: 8

encoder_params:
  chk: ""
  fc_hidden1: 1500
  drop_out: 0.5
  torch_script_path: ""
  freeze: True

decoder_params:
  chk: ""
  h_rnn_layers: 2
  rnn_nodes: 128
  fc_dim: 32
  drop_out: 0.5
  num_outputs: 2
  torch_script_path: ""

optimizer:
  lr: 1e-3

scheduler:
  gamma: 0.9
