dataset:
  data_path: "./data/dataset/"
  VA_label_path: "./data/annotations_VA/"
  seq_len: 80
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

train_params:
  seed: 2021
  batch_size: 128
  n_epochs: 15
  gpu_id: 0
  num_workers: 8

encoder_params:
  fc_hidden1: 512
  fc_hidden2: 512
  drop_out: 0.3
  embedding_dim: 300

decoder_params:
  h_rnn_layers: 2
  rnn_nodes: 128
  fc_dim: 32
  drop_out: 0.3
  num_outputs: 2

optimizer:
  lr: 1e-3
