dataset:
  data_path: "./data/dataset/"
  VA_label_path: "./data/annotations_VA/"
  seq_len: 80
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  size: 96

train_params:
  debug: False
  seed: 2021
  gpu_id: 0
  batch_size: 128
  n_epochs: 15
  criterion: ccc
  num_workers: 8

encoder_params:
  chk: ""
  fc_hidden1: 1500
  drop_out: 0.5
  torch_script_path: ""

decoder_params:
  chk: ""
  h_rnn_layers: 2
  rnn_nodes: 128
  fc_dim: 32
  drop_out: 0.5
  num_outputs: 2
  torch_script_path: ""

optimizer:
  lr: 1e-3
